
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToMad")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToMad", targetNamespace = "http://ws/", className = "proxy.ConversionEuroToMad")
    @ResponseWrapper(localName = "ConversionEuroToMadResponse", targetNamespace = "http://ws/", className = "proxy.ConversionEuroToMadResponse")
    @Action(input = "http://ws/BanqueService/ConversionEuroToMadRequest", output = "http://ws/BanqueService/ConversionEuroToMadResponse")
    public double conversionEuroToMad(
        @WebParam(name = "Montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws/", className = "proxy.GetCompteResponse")
    @Action(input = "http://ws/BanqueService/getCompteRequest", output = "http://ws/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "Code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeComptes", targetNamespace = "http://ws/", className = "proxy.ListeComptes")
    @ResponseWrapper(localName = "listeComptesResponse", targetNamespace = "http://ws/", className = "proxy.ListeComptesResponse")
    @Action(input = "http://ws/BanqueService/listeComptesRequest", output = "http://ws/BanqueService/listeComptesResponse")
    public List<Compte> listeComptes();

}
